### ISSUE TITLE
can I use motor(mongodb) with this?

### ISSUE THREAD

**Issue by Barceloch** [python-turbulette/turbulette#41]
I find this project very interesting, I have been looking for something similar but that can use mongodb as a database.

Is it possible to use motor for mongodb with turbulette?

**Comment by gazorby** [comment]
Thanks for your interest in Turbulette!

Currently, Turbulette use GINO as ORM, and it's possible to use redis through [async-caches](https://github.com/rafalp/async-caches) for caching purposes.

We could add bindings to mongodb using motor, but keep in mind that Turbulette use GINO to interact with the main data source, so you will still have to setup a postgres db if you want to use the built-in auth app for example.

I think the work needed to make it real isn't that big :
- Provide a nice way to configure multiple databases in settings
- Expose a `MotorClient` in turbulette's `db` module

If we add support for more databases, I wonder if it would be a good idea to make db clients optional dependencies (including GINO?) so users could choose the one that best suits their needs, like in your case.

**Comment by Barceloch** [comment]
> I think the work needed to make it real isn't that big :
> 
>     * Provide a nice way to configure multiple databases in settings
> 
>     * Expose a `MotorClient` in turbulette's `db` module
> 
> 
> If we add support for more databases, I wonder if it would be a good idea to make db clients optional dependencies (including GINO?) so users could choose the one that best suits their needs, like in your case.
...
Well, I think that if it would be a great idea, it would also give users much more flexibility when choosing their db.

On the other hand, have you thought about including "subscription" and "websokects" in the core of Turbulette?

**Comment by gazorby** [comment]
I will think about it ;)

All the GraphQL binding is handled by [Ariadne](https://ariadnegraphql.org/), which support subscription operations via websockets. You can see more details [here](https://ariadnegraphql.org/docs/subscriptions).

You make me realize that `subscriptionType` isn't even defined in Turbulette root_types, and isn't registered in the schema, meaning that you can't use subscription in Turbulette right now. Will fix this ASAP!

Otherwise, there will be nothing special about using subscriptions in Turbulette, you would just follow Ariadne's docs as long as the code live in the resolvers package.

**Comment by Barceloch** [comment]
Ok, :) I will wait for you fix it.

**Comment by gazorby** [comment]
Hi @Barceloch ,

v0.4.0 fix websocket / subscription, it should be ready to use.

As `Query` and `Mutation`, `Subscription` is already defined in Turbulette so you can extend it in your app schema :

```graphql
extend type Subscription {
	count: Int!
}
```

For the resolver part, use `subscription` from the `turbulette` package and follow Ariadne docs :

```graphql
from turbulette import subscription

@subscription.source("counter")
async def counter_generator(obj, info):
    for i in range(5):
        await asyncio.sleep(1)
        yield i


@subscription.field("counter")
def counter_resolver(count, info):
    return count + 1
```

**Comment by Barceloch** [comment]
> Hi @Barceloch ,
> 
> v0.4.0 fix websocket / subscription, it should be ready to use.
> 
> As `Query` and `Mutation`, `Subscription` is already defined in Turbulette so you can extend it in your app schema :
> 
> ```graphql
> extend type Subscription {
> 	count: Int!
> }
> ```
> 
> For the resolver part, use `subscription` from the `turbulette` package and follow Ariadne docs :
> 
> ```graphql
> from turbulette import subscription
> 
> @subscription.source("counter")
> async def counter_generator(obj, info):
>     for i in range(5):
>         await asyncio.sleep(1)
>         yield i
> 
> 
> @subscription.field("counter")
> def counter_resolver(count, info):
>     return count + 1
> ```

nice... in some days I will test this... ;)
